language: haskell

before_install:
    - export START=`pwd`
    - sudo apt-get update -qq
    - sudo apt-get --no-install-recommends install darcs libgmp3-dev libgmp3c2 freeglut3 freeglut3-dev
    - sudo apt-get build-dep ghc
    - sudo apt-get clean
    - cd
    - wget http://hdiff.luite.com/ghcjs/ghcjs-test.tar.xz
    - tar -xJf $HOME/ghcjs-test.tar.xz --strip-components=1
    - rm ghcjs-test.tar.xz
    - export PATH=$HOME/ghc/bin:$HOME/.cabal/bin:$HOME/jsshell:$HOME/node/bin:$PATH
    - cd $HOME/.cabal/bin
    - wget http://hdiff.luite.com/ghcjs/TestRunner
    - chmod 755 TestRunner
    - hash -r
    - cd $START

install:
    - pwd
    - cabal install -f-compiler-only -fdisable-optimizer
    - ghcjs-boot --reboot
    - cabal install --ghcjs random syb transformers text parallel QuickCheck old-time vector
    - cd
    - git clone git://github.com/ghcjs/ghcjs-prim.git
    - cd ghcjs-prim
    - cabal install --ghcjs
    - cd
    - git clone git://github.com/ghcjs/ghcjs-base.git
    - cd ghcjs-base
    - cabal install --ghcjs
    - cd $HOME/.ghcjs/x86*
    - git clone git://github.com/ghcjs/shims.git

script:
    - pwd
    - cd $HOME/ghcjs
    - TestRunner



