jobs:
- job: Linux_Cabal
  timeoutInMinutes: 300
  pool:
    vmImage: ubuntu-16.04
  steps:
  - bash: |
      git submodule sync
      git submodule update --init --recursive
    displayName: Sync submodules
  - bash: |
      sudo add-apt-repository ppa:hvr/ghc -y
      sudo apt -y update
      sudo apt install build-essential cabal-install-3.0 ghc-8.6.5 happy-1.19.5 alex-3.1.7 -y
      sudo update-alternatives --config opt-ghc
      sudo update-alternatives --config opt-cabal
      sudo update-alternatives --config opt-alex
      sudo update-alternatives --config opt-happy
      nvm install 10
      mkdir -p ~/.local/bin
    displayName: Install Dependencies
  - bash: |
      export PATH=$PWD/.cabal-sandbox/bin:$HOME/.cabal/bin:/opt/ghc/bin:/opt/alex/bin:/opt/happy/bin:$PATH
      cabal update
    displayName: Update Cabal package list
  - bash: |
      export PATH=$PWD/.cabal-sandbox/bin:$HOME/.cabal/bin:/opt/ghc/bin:/opt/alex/bin:/opt/happy/bin:$PATH
      ./utils/makePackages.sh
      ./utils/makeSandbox.sh
      cabal v1-install -j1 --only-dependencies --enable-tests --enable-benchmarks
      cabal v1-install --enable-tests --enable-benchmarks -v -j1 --ghc-options="+RTS -c -RTS"
    displayName: Install GHCJS
  - bash: |
      export PATH=$PWD/.cabal-sandbox/bin:$HOME/.cabal/bin:/opt/ghc/bin:/opt/alex/bin:/opt/happy/bin:$PATH
      ghcjs-boot -s ./lib/boot
    displayName: Install GHCJS boot libraries
  - bash: |
      export PATH=$PWD/.cabal-sandbox/bin:$HOME/.cabal/bin:/opt/ghc/bin:/opt/alex/bin:/opt/happy/bin:$PATH
      TESTRUNNER="./dist/dist-sandbox-*/build/test/test"
      "$TESTRUNNER"--with-spidermonkey=none --with-javascriptcore=none --with-node="node"
    displayName: Run Test Suite
